---
- hosts: jenkins
  tasks:
    - name: Remove any existing corrupted Jenkins repository file
      file:
        path: /etc/apt/sources.list.d/jenkins.list
        state: absent

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins GPG key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Update apt cache after adding Jenkins repository
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins is started and enabled
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Add user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Ensure Docker is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install dependencies
      apt:
        name:
          - unzip
          - curl
        state: present

    - name: Download AWS CLI
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI package
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Install AWS CLI
      command: "/tmp/aws/install"

    - name: Install Git
      apt:
        name: git
        state: present


    - name: restart jenkins
      service:
        name: jenkins
        state: restarted

    - name: Download the CloudWatch agent installer
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/linux/amd64/latest/AmazonCloudWatchAgent.zip
        dest: /tmp/AmazonCloudWatchAgent.zip

    - name: Install unzip package
      package:
        name: unzip
        state: present

    - name: Unzip the CloudWatch agent installer
      unarchive:
        src: /tmp/AmazonCloudWatchAgent.zip
        dest: /tmp/
        remote_src: yes

    - name: Install the CloudWatch agent
      shell: |
        cd /tmp
        ./install.sh
      register: install_result
      changed_when: '"Successfully installed the CloudWatch Agent" in install_result.stdout'

    - name: Start the CloudWatch agent
      service:
        name: amazon-cloudwatch-agent
        state: started
        enabled: yes